### ISSUE TITLE
plot.sh script does not work

### ISSUE THREAD

**Issue by achjaj** [brianlow/plotter#1]
When I run `./plot-sh flower/flower.svg` I get this error:

```
flower/flower.svg -> flower/flower.gcode

Warning: entry point could not be loaded. Contact its author for help.

 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vpype_cli/cli.py", line 205, in cli
    cast(click.Group, ctx.command).add_command(entry_point.load())
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/vpype_gcode/gwrite.py", line 14, in <module>
    vp.CONFIG_MANAGER.load_config_file(str(Path(__file__).parent / "bundled_configs.toml"))
AttributeError: module 'vpype' has no attribute 'CONFIG_MANAGER'
```

Python version: 3.10.5
vpype version: 1.11.0

**Comment by achjaj** [comment]
It's a bug in `vpype-gcode` package, the script works with vpype 1.10.0
